### ISSUE TITLE
Uncaught Error: java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by NsAveek** [SelfnessAid/Expo.io-google-cloud-ocr#1]
Uncaught Error: java.net.SocketTimeoutException:failed to connect to /192.168.56.1(port 19000) after 10000ms

Getting the above error when running in real android device .The project runs good in genymotion emulator. What could be the possible cause ?

**Comment by WebMobi59** [comment]
You need to set same branch on laptop and PC.
